### ISSUE TITLE
Friendships (2nd Iteration)

### ISSUE THREAD

**Issue by andrearrrr** [andrearrrr/cmpt276-11#24]

**Comment by Bryce-C** [comment]
Branch for friends complete.

Currently user has ability to navigate to a user page and friend that user by clicking the big "Add friend" button at the top.

Friendships are one way (You can friend a user, but they are not your mutual friend until they friend you back)

Main 'user/userid/friends' page shows only mutual friends (you friended them, they friended you

You can also access outgoing friends and incoming friends through their pages as well (linked to those pages on user profile currently)

There are a few tests, perhaps not as thourough as possible, but in local testing everything seems to work.
